spring.application.name=scheduler
server.port=60000

spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:26257/dist_jobs_scheduler?sslmode=disable
spring.datasource.username=root
spring.datasource.password=
spring.datasource.hikari.maximum-pool-size=10

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

ats.targets[0].ats=greenhouse
ats.targets[0].slug=stripe
ats.targets[1].ats=greenhouse
ats.targets[1].slug=cloudflare
ats.targets[2].ats=ashby
ats.targets[2].slug=openai
ats.targets[3].ats=ashby
ats.targets[3].slug=ramp
ats.targets[4].ats=lever
ats.targets[4].slug=palantir
ats.targets[5].ats=smartrecruiters
ats.targets[5].slug=ServiceNow
ats.targets[6].ats=recruitee
ats.targets[6].slug=channable
ats.targets[7].ats=workable
ats.targets[7].slug=netdata
ats.targets[8].ats=teamtailor
ats.targets[8].slug=tibber
ats.targets[9].ats=workday
ats.targets[9].slug={"tenant":"nvidia","dc":"wd5","site":"NVIDIAExternalCareerSite"}
ats.targets[10].ats=remotive
ats.targets[10].slug=software-dev
ats.targets[11].ats=remoteok
ats.targets[12].ats=arbeitnow